---
swagger: "2.0"
info:
  description: "Scooters"
  version: "1.0.0"
  title: "Scooter API"
host: "0.0.0.0:8080"
basePath: "/v2"
tags:
- name: "employees"
  description: "Employee collection"
schemes:
- "http"
paths:
  /scooters:
    get:
      tags:
      - "scooters"
      summary: "Get all available scooters"
      description: ""
      operationId: "get_available_scooters"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful"
          schema:
            $ref: "#/definitions/ArrayOfScooter"
      x-swagger-router-controller: "swagger_server.controllers.scooters_controller"
    post:
      tags:
      - "scooters"
      summary: "Add a new scooter"
      description: ""
      operationId: "add_scooter"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Scooter data"
        required: true
        schema:
          $ref: "#/definitions/Scooter"
      responses:
        "200":
          description: "Succesfully added a new scooter"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.scooters_controller"
  /scooters/{licensePlate}:
    get:
      tags:
      - "scooters"
      summary: "Find scooter by license plate"
      description: "Returns a single scooter"
      operationId: "get_scooter_by_license_plate"
      produces:
      - "application/json"
      parameters:
      - name: "licensePlate"
        in: "path"
        description: "License plate of scooter to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Scooter"
        "400":
          description: "Invalid license plate supplied"
        "404":
          description: "License plate not found"
      x-swagger-router-controller: "swagger_server.controllers.scooters_controller"
    put:
      tags:
      - "scooters"
      summary: "Update an existing scooter"
      description: ""
      operationId: "update_scooter"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "licensePlate"
        in: "path"
        description: "License plate of scooter to be updated"
        required: true
        type: "string"
      responses:
        "200":
          description: "Succesfully updated the scooter"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Scooter not found"
        "405":
          description: "Validation exception"
      x-swagger-router-controller: "swagger_server.controllers.scooters_controller"
    delete:
      tags:
      - "scooters"
      summary: "Deletes a scooter"
      description: ""
      operationId: "delete_scooter"
      produces:
      - "application/json"
      parameters:
      - name: "licensePlate"
        in: "path"
        description: "License plate of the scooter to delete"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid license plate supplied"
        "404":
          description: "Scooter not found"
      x-swagger-router-controller: "swagger_server.controllers.scooters_controller"
definitions:
  Scooter:
    type: "object"
    required:
    - "batteryPercentage"
    - "latitude"
    - "licensePlate"
    - "longitude"
    - "status"
    properties:
      licensePlate:
        type: "string"
        example: "X4CNPC"
      latitude:
        type: "number"
        example: 10.4443999999999999062083588796667754650115966796875
      longitude:
        type: "number"
        example: 72.55549999999999499777914024889469146728515625
      batteryPercentage:
        type: "number"
        example: 85
      status:
        type: "string"
        example: "BUSY"
    xml:
      name: "Scooter"
    example:
      licensePlate: "X4CNPC"
      latitude: 10.4443999999999999062083588796667754650115966796875
      batteryPercentage: 85
      longitude: 72.55549999999999499777914024889469146728515625
      status: "BUSY"
  ArrayOfScooter:
    type: "array"
    items:
      $ref: "#/definitions/Scooter"
